services:
  springboot-app:
    image: telefoni-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/telefoni-bdd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hello
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: telefoni-bdd
      MYSQL_PASSWORD: hello
      MYSQL_ROOT_PASSWORD: hello
    ports:
      - "3307:3306"
